workflows:
  android-release:
    name: Android Release APK
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 17
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install

      - name: Setup Expo
        script: |
          cd frontend
          npx expo prebuild --platform android --clean

      - name: Build Release APK
        script: |
          cd frontend/android
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - frontend/android/app/build/outputs/**/*.apk
