workflows:
  android-release:
    name: Android Release APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      java: 17
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      
      - name: Setup Expo
        script: |
          cd frontend
          npx expo prebuild --platform android --clean
      
      - name: Build Release APK
        script: |
          cd frontend/android
          ./gradlew assembleRelease
    
    artifacts:
      - frontend/android/app/build/outputs/apk/release/*.apk
