workflows:
  android-release:
    name: Android Release AAB
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 17
      node: 18
      groups:
        - android_credentials
      vars:
        EXPO_PUBLIC_BACKEND_URL: "https://alter-ego-app-1.preview.emergentagent.com"
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install

      - name: Setup Expo
        script: |
          cd frontend
          npx expo prebuild --platform android --clean

      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/frontend/android/app/keystore.jks
          cat >> $CM_BUILD_DIR/frontend/android/gradle.properties <<EOF
          MYAPP_UPLOAD_STORE_FILE=keystore.jks
          MYAPP_UPLOAD_KEY_ALIAS=$CM_KEY_ALIAS
          MYAPP_UPLOAD_STORE_PASSWORD=$CM_KEYSTORE_PASSWORD
          MYAPP_UPLOAD_KEY_PASSWORD=$CM_KEY_PASSWORD
          EOF

      - name: Build Release AAB
        script: |
          cd frontend/android
          chmod +x gradlew
          ./gradlew bundleRelease

    artifacts:
      - frontend/android/app/build/outputs/bundle/release/*.aab
      - frontend/android/app/build/outputs/apk/release/*.apk
    
    publishing:
      email:
        recipients:
          - hakan.dalmis13@gmail.com
        notify:
          success: true
          failure: true

  android-debug:
    name: Android Debug APK
    max_build_duration: 45
    instance_type: linux_x2
    environment:
      java: 17
      node: 18
      vars:
        EXPO_PUBLIC_BACKEND_URL: "https://alter-ego-app-1.preview.emergentagent.com"
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install

      - name: Setup Expo
        script: |
          cd frontend
          npx expo prebuild --platform android --clean

      - name: Build Debug APK
        script: |
          cd frontend/android
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - frontend/android/app/build/outputs/apk/**/*.apk
