workflows:
  android_release_aab:
    name: Android Release AAB (Play Store)
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 17
      node: 20
      groups:
        - android-signing
      vars:
        EXPO_PUBLIC_BACKEND_URL: "https://alter-ego-app-1.preview.emergentagent.com"

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          yarn install --network-timeout 100000

      - name: Expo Prebuild (Generate Android Project)
        script: |
          cd frontend
          npx expo prebuild --platform android --clean

      - name: Decode Keystore
        script: |
          KEYSTORE_PATH="$CM_BUILD_DIR/frontend/android/app/release-keystore.jks"
          echo "$CM_KEYSTORE" | base64 --decode > "$KEYSTORE_PATH"
          echo "✅ Keystore decoded to: $KEYSTORE_PATH"
          ls -la "$KEYSTORE_PATH"

      - name: Build Release AAB (Injected Signing)
        script: |
          set -euo pipefail
          cd frontend/android
          chmod +x gradlew

          echo "🔨 Starting Release AAB build..."
          ./gradlew :app:bundleRelease --stacktrace \
            -Pandroid.injected.signing.store.file="$CM_BUILD_DIR/frontend/android/app/release-keystore.jks" \
            -Pandroid.injected.signing.store.password="$CM_KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$CM_KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$CM_KEY_PASSWORD"

          echo ""
          echo "=== ✅ Build Complete ==="
          AAB_FILE=$(find app/build/outputs -name "*.aab" -type f | head -1)
          if [ -n "$AAB_FILE" ]; then
            echo "📦 AAB Location: $AAB_FILE"
            ls -lh "$AAB_FILE"
          else
            echo "❌ ERROR: No AAB file found!"
            exit 1
          fi

    artifacts:
      - frontend/android/app/build/outputs/bundle/release/*.aab
      - frontend/android/app/build/outputs/mapping/release/mapping.txt

    publishing:
      email:
        recipients:
          - hakan.dalmis13@gmail.com
        notify:
          success: true
          failure: true

  android_debug_apk:
    name: Android Debug APK (Testing)
    max_build_duration: 45
    instance_type: linux_x2
    environment:
      java: 17
      node: 20
      vars:
        EXPO_PUBLIC_BACKEND_URL: "https://alter-ego-app-1.preview.emergentagent.com"

    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          yarn install --network-timeout 100000

      - name: Expo Prebuild
        script: |
          cd frontend
          npx expo prebuild --platform android --clean

      - name: Build Debug APK
        script: |
          set -euo pipefail
          cd frontend/android
          chmod +x gradlew
          ./gradlew :app:assembleDebug --stacktrace

          echo "✅ Debug APK built!"
          APK_FILE=$(find app/build/outputs/apk/debug -name "*.apk" -type f | head -1)
          if [ -n "$APK_FILE" ]; then
            echo "📦 APK Location: $APK_FILE"
            ls -lh "$APK_FILE"
          else
            echo "❌ ERROR: No APK file found!"
            exit 1
          fi

    artifacts:
      - frontend/android/app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - hakan.dalmis13@gmail.com
        notify:
          success: true
          failure: true
