workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      node: 18
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install

      - name: Prebuild Android
        script: |
          cd frontend
          npx expo prebuild --clean

      - name: Build Debug APK
        script: |
          cd frontend/android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - frontend/android/app/build/outputs/**/*.apk
